version: '3'

services:
  horarios:
    image: node
    container_name: horarios
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "443:443"
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    command: bash -c "cd app; npm run run-prod"
