version: '3'

services:
  horarios:
    image: node
    container_name: horarios
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - nginx_network
    command: cd app; npm run run-prod